# SPDX-FileCopyrightText: 2025 United Security Providers AG, Switzerland
#
# SPDX-License-Identifier: GPL-3.0-only

apiVersion: waap.core.u-s-p.ch/v1alpha1
kind: CoreWaapService
metadata:
  name: nextjs-app-usp-core-waap
  namespace: nextjs
spec:
  routes:
    - match:
        path: /
        pathType: PREFIX
      backend:
        address: nextjs-svc.nextjs.svc.cluster.local
        port: 8080
        protocol:
          selection: h1
