# SPDX-FileCopyrightText: 2025 United Security Providers AG, Switzerland
#
# SPDX-License-Identifier: GPL-3.0-only

---
apiVersion: v1
kind: Namespace
metadata:
  name:  petstore
---
apiVersion: v1
kind: Pod
metadata:
  name: petstore
  namespace: petstore
  labels:
    app.kubernetes.io/name: petstore
spec:
  containers:
  - name: petstore
    image: swaggerapi/petstore:1.0.7
    env:
      - name: SWAGGER_BASE_PATH
        value: /api
      - name: SWAGGER_URL
        value: http://localhost:8080
      - name: SWAGGER_HOST
        value: http://petstore.petstore.svc:8080
    ports:
      - name: http
        containerPort: 8080
        protocol: TCP
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 500m
---
kind: Service
apiVersion: v1
metadata:
  name: petstore
  namespace: petstore
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: petstore
  ports:
  - name: http
    port: 8080
    targetPort: 8080
