apiVersion: v1
kind: ConfigMap
metadata:
  name: core-waap-static-resources
  namespace: juiceshop
data:
  error5xx.html: |
    <!DOCTYPE html>
    <html>
    <body style="background-color:#303030; font-family: Roboto, Helvetica Neue, sans-serif;">
      <div
        style="width: 60%%; position: absolute; top: 30%%; left: 20%%; background-color:#424242;color:white;padding:20px; text-align: center;">
        <h2>Error</h2>
        <p>Please retry to access the webpage. In case the request is not successful get in touch with support@...
          providing the information below.</p>
        <div style=" text-align:left; width: 40%%; margin: auto;" ;>
          <b>Backend status code:</b> %RESPONSE_CODE% <br>
          <b>Client request id:</b> %REQ(X-REQUEST-ID)% <br>
          <b>Timestamp:</b> %START_TIME%
        </div>
        <br>
        <img src="/assets/public/images/JuiceShop_Logo.png" width="150" height="180">
      </div>
    </body>
    </html>
