apiVersion: v1
kind: Pod
metadata:
  name: juiceshop
  labels:
    app.kubernetes.io/name: juiceshop
spec:
  containers:
  - name: juiceshop
    image: bkimminich/juice-shop
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
