# SPDX-FileCopyrightText: 2025 United Security Providers AG, Switzerland
#
# SPDX-License-Identifier: GPL-3.0-only

apiVersion: waap.core.u-s-p.ch/v1alpha1
kind: CoreWaapService
metadata:
  name: juiceshop-usp-core-waap
  namespace: juiceshop
spec:
  paranoiaLevel: 2
  requestRuleExceptions:
    - location: /rest/basket/.+/checkout$
      regEx: true
      requestPartName: json.couponData
      requestPartType: ARGS_POST
      ruleIds:
        - 942120
      metadata:
        createdBy: killercoda
        date: "2025-08-22"
  websocket: true
  routes:
    - match:
        path: "/"
        pathType: "PREFIX"
      backend:
        address: juiceshop
        port: 8080
        protocol:
          selection: h1
